ALTER TABLE `forbes`.`fb_news` MODIFY COLUMN `user` VARCHAR(64)  CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '当前使用者',
 MODIFY COLUMN `last_user` VARCHAR(64)  CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '上一使用者',
 MODIFY COLUMN `news_info` TEXT  CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '原因说明';
