CREATE TABLE `forbes`.`fb_investor_sign` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100),
  `mobile` VARCHAR(45),
  `email` VARCHAR(100),
  `post` VARCHAR(100),
  `phone` VARCHAR(100),
  `qq` VARCHAR(45),
  `msn` VARCHAR(100),
  `item_name` VARCHAR(255),
  `industry` VARCHAR(255),
  `item_type` VARCHAR(45),
  `item_money` VARCHAR(100),
  `item_description` TEXT,
  `item_url` VARCHAR(100),
  `item_doc` VARCHAR(45),
  `company_name` VARCHAR(255),
  `company_size` VARCHAR(255),
  `company_created` VARCHAR(100),
  `company_location` VARCHAR(100),
  `zip` VARCHAR(45),
  `capital` VARCHAR(100),
  PRIMARY KEY (`id`)
)