CREATE TABLE `forbes_ad`.`fb_ad` (
  `id` int  NOT NULL AUTO_INCREMENT,
  `name` varchar(256)  NOT NULL,
  `code` char(20)  NOT NULL COMMENT '广告代码',
  `channel_id` int ,
  `banner_id` int ,
  `target_url` varchar(256) ,
  `title` varchar(256) ,
  `image` varchar(256) ,
  `flash` varchar(256) ,
  `video` varchar(256) ,
  `start_date` datetime ,
  `end_date` datetime ,
  `start_hour` varchar(20) ,
  `end_hour` varchar(20) ,
  `show_price` float  COMMENT '千次展示价格',
  `click_price` float  COMMENT '千次点击价格',
  `pop_price` float  COMMENT '千次弹框价格',
  `description` varchar(500)  COMMENT '描述',
  `is_adopt` bool  COMMENT '是否发布',
  PRIMARY KEY (`id`),
  INDEX `new_index`(`banner_id`),
  INDEX `new_index1`(`channel_id`)
);
