CREATE TABLE `forbes`.`fb_investor_sign_income` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `sign_id` INTEGER UNSIGNED NOT NULL,
  `year` INTEGER UNSIGNED NOT NULL,
  `income` INTEGER UNSIGNED NOT NULL,
  `type` INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY (`id`)
)