CREATE TABLE  `forbes`.`zzh_member` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) DEFAULT NULL,
  `mobile` varchar(45) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `post` varchar(100) DEFAULT NULL,
  `phone` varchar(100) DEFAULT NULL,
  `qq` varchar(45) DEFAULT NULL,
  `msn` varchar(100) DEFAULT NULL,
  `item_name` varchar(255) DEFAULT NULL,
  `industry` varchar(255) DEFAULT NULL,
  `item_type` varchar(45) DEFAULT NULL,
  `item_money` varchar(100) DEFAULT NULL,
  `item_description` text,
  `item_url` varchar(100) DEFAULT NULL,
  `item_doc` varchar(45) DEFAULT NULL,
  `company_name` varchar(255) DEFAULT NULL,
  `company_size` varchar(255) DEFAULT NULL,
  `company_created` varchar(100) DEFAULT NULL,
  `company_location` varchar(100) DEFAULT NULL,
  `zip` varchar(45) DEFAULT NULL,
  `capital` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=25 DEFAULT CHARSET=utf8
